name: FavmeMusic Hunter

on:
  schedule:
    - cron: '*/30 * * * *' # اجرای خودکار هر ۳۰ دقیقه
  workflow_dispatch: # دکمه اجرای دستی در تب Actions

permissions:
  contents: write # اجازه به گیت‌هاب برای ذخیره فایل تاریخچه

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto google-generativeai openai jdatetime

      - name: Start Hunting
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
          CEREBRAS_KEY: ${{ secrets.CEREBRAS_KEY }}
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
        run: python music_hunter.py

      - name: Save History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hunter_state.json
          git commit -m "Update music history [skip ci]" || echo "No changes to commit"
          git push
